---
title: "report"
author: "Szymon Winnicki"
date: "24/04/2021"
runtime: shiny
output: html_document
---

```{r echo = FALSE}
library(tidyverse)
library(viridis)
library(cowplot)
library(shiny)


locs_sp <- readRDS('data/locs_sp.RDS')
```

```{r echo = FALSE}
# selectInput("year", label = "Year:",
#               choices = unique(locs_sp$year), selected = 2018)

sliderInput("year", "Year:",
                  min = min(locs_sp$year), max = max(locs_sp$year),
                  round = T, sep = '', ticks = F,
                  value = 2018)
```


```{r echo = FALSE}
  # define plot function
plot_metrics <- function (var, year, title, caption, legend, breaks) {
  var <- enquo(var)
  ggplot() +
    geom_polygon(data = locs_sp[locs_sp$year == year,], aes(x=long, y=lat, group=group, fill=!!var), colour='black', size=1, alpha=0.9) +
    theme_bw() +
    theme(
      plot.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_blank()
    ) +
    coord_fixed() +
    scale_fill_viridis(trans = "log1p",
                       breaks = breaks, labels = breaks
    ) +
    theme_void() +
    labs(
      caption = caption,
      title = title,
      fill = legend
    ) +
    theme(
      plot.title = element_text(color="#000000", face="bold", size=12, hjust=0),
      plot.caption = element_text(color="#000000", face="bold", size=8, hjust=1),
      plot.margin = unit(c(0.5,0.5,0.5,0.5), "cm"),
      legend.title = element_text(color="#505050", face="bold", size=10, hjust=1),
      legend.text = element_text(color="#505050", size=8, angle = 0),
      legend.position = 'bottom',
      legend.key.size = unit(0.3, "cm")
    ) +
    guides(
      fill = guide_colourbar(
        ticks.colour = "white", 
        ticks.linewidth = 1.2, 
        barwidth=15, 
        label.position="bottom"))
}


renderPlot({
  a <- plot_metrics(check_in, input$year, 'a) migrants', 'Data Source: Polish Statistical Office', '# of migrants', c(0, 1, 5, 10, 25, 50, 100, 250, 750))
  b <- plot_metrics(pop_density,input$year, 'b) population density', 'Data Source: Polish Statistical Office', '', c(0, 0.5, 1, 2, 3, 5, 7, 10, 15, 20, 30)) + 
    labs(fill = expression(bold(paste('# of people / ', km^2))))
  c <- plot_metrics(dist, input$year, 'c) distance', 'Data Source: Google Maps', 'km', c(10, 12, 15, 20, 25, 30, 40, 50))
  d <- plot_metrics(income, input$year, 'd) income per capita', 'Data Source: Polish Statistical Office', 'ratio', c(0.3, 0.5, 0.75, 1, 1.25, 1.5, 2))

plot_grid(a, b, c, d, align = 'hv', greedy=F)
},
height = 700)
```